# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


pool: AWS

steps:
- script: |
    git branch -a
    git log -p --shortstat --format="%h, %f" master...1.0.1 >git_commits_log5.txt
  displayName: 'Run a multi-line script'
