# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    mkdir test && cd test
    git init .
    git config --global user.name "yashwanthk147"
    git config --global user.email "yashwanthkotha147@gmail.com"
    #git config --global github.token "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"

    git remote add origin https://github.com/yashwanthk147
    git clone https://github.com/yashwanthk147/Test-PR.git
    git checkout main
    git branch
    git log -p --shortstat --format="%h, %f" main...v1.0.1 >git_commits_log5.txt
  displayName: 'Run a multi-line script'
